FROM golang

EXPOSE 9095 9096

WORKDIR /app

COPY . .

RUN go mod tidy

RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o goapp .

CMD ["/go/bin/dlv", "--listen=:9096", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/goapp" ]